name: app
publish_to: 'none'

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
