name: debug
description: 'Application to masnually evaluate some scenarios.'
publish_to: 'none'

resolution: workspace

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  dartantic_ai: ^3.1.0
  flutter:
    sdk: flutter
  json_schema_builder: ^0.1.3
  logging: ^1.3.0
  shared:
    path: ../shared

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
