name: app
publish_to: 'none'

resolution: workspace

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  dartantic_ai: ^3.0.0
  flutter:
    sdk: flutter
  genui:
    git:
      # url: https://github.com/polina-c/genui
      # path: packages/genui
      # ref: v09-catalog
      url: https://github.com/flutter/genui
      path: packages/genui
      ref: feature/v0.9-migration
  json_schema_builder: ^0.1.3
  logging: ^1.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
